### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thomassth** [thomassth/to-bus-stations#1]
- [x] Summarize all stops into 1 file
- [x] (front end?) figure out a (good) way to calculate closest points
- [x] (front end) use the web indexed DB
- [x] #2
